import type { HotelOption } from "@/lib/types";

function hotel(
  partial: Omit<HotelOption, "source" | "mapsUrl"> & { mapsQuery?: string },
): HotelOption {
  const query = partial.mapsQuery ?? partial.name;
  return {
    id: partial.id,
    name: partial.name,
    area: partial.area,
    lat: partial.lat,
    lng: partial.lng,
    blurb: partial.blurb,
    priceBand: partial.priceBand,
    station: partial.station,
    rating: partial.rating,
    source: "curated",
    mapsUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`,
  };
}

export const HOTELS: Record<string, HotelOption[]> = {
  Asakusa: [
    hotel({
      id: "nono-asakusa",
      name: "Onyado Nono Asakusa Natural Hot Spring",
      area: "Asakusa",
      lat: 35.7137,
      lng: 139.7986,
      blurb:
        "The Tokyo base with a natural hot-spring bath, a few minutes from Sensō-ji. The big bath is shared; the room itself is an ordinary hotel room, not a private tub. Staying here all week means the suitcases never move.",
      priceBand: "Shared natural spring · about $130–190 a night · ¥20,000–28,000",
      station: "Asakusa",
    }),
    hotel({
      id: "prostyle-asakusa",
      name: "Prostyle Ryokan Tokyo Asakusa",
      area: "Asakusa",
      lat: 35.7128,
      lng: 139.7904,
      blurb:
        "The closest thing to a private tub in Asakusa. Ask for the Japanese-style king, the corner twin, or the suite. Those rooms have a private bath, partly open to the air. It is heated tap water, not a natural hot spring. The other rooms do not have it.",
      priceBand: "Private bath in three room types · about $400–600 · ¥60,000–90,000",
      station: "Asakusa",
      mapsQuery: "Prostyle Ryokan Tokyo Asakusa",
    }),
    hotel({
      id: "cyashitsu-asakusa",
      name: "Cyashitsu Ryokan Asakusa",
      area: "Asakusa",
      lat: 35.7164,
      lng: 139.7948,
      blurb:
        "One room has its own open-air bath, and every guest can reserve the rooftop cypress bath. Both use heated water, not spring water. The rooms are tea-room small. Book the open-air room by name or it will be gone.",
      priceBand: "One private open-air room · about $300–450 · ¥45,000–68,000",
      station: "Asakusa",
      mapsQuery: "Cyashitsu Ryokan Asakusa",
    }),
    hotel({
      id: "richmond-asakusa",
      name: "Richmond Hotel Premier Asakusa",
      area: "Asakusa",
      lat: 35.7114,
      lng: 139.7964,
      blurb: "A short walk from Asakusa Station on the through-line from Haneda. The desk will hold bags before the room is ready.",
      priceBand: "Mid range",
      station: "Asakusa",
    }),
    hotel({
      id: "gate-kaminarimon",
      name: "The Gate Hotel Kaminarimon",
      area: "Asakusa",
      lat: 35.711,
      lng: 139.796,
      blurb: "Beside the Kaminarimon gate. Useful if Sensō-ji is the first thing you want after the bags are down.",
      priceBand: "Splurge",
      station: "Asakusa",
    }),
    hotel({
      id: "mitsui-asakusa",
      name: "Mitsui Garden Hotel Asakusa",
      area: "Asakusa",
      lat: 35.7135,
      lng: 139.7945,
      blurb: "A quieter block just off Nakamise. Straightforward business-hotel check-in at 3:00 pm, with free bag storage before that.",
      priceBand: "Mid range",
      station: "Asakusa",
    }),
  ],
  "Ueno & Yanaka": [
    hotel({
      id: "mitsui-ueno",
      name: "Mitsui Garden Hotel Ueno",
      area: "Ueno & Yanaka",
      lat: 35.7078,
      lng: 139.7735,
      blurb: "Next to Ueno Park, so Rikugien, the museum, and Yanaka are a walk or one stop away.",
      priceBand: "Mid range",
      station: "Ueno",
    }),
    hotel({
      id: "nui-kuramae",
      name: "Nui. Hostel & Bar Lounge",
      area: "Ueno & Yanaka",
      lat: 35.7032,
      lng: 139.7915,
      blurb: "A simpler stay toward Kuramae if you want the east side without a big hotel.",
      priceBand: "Simple",
      station: "Kuramae",
    }),
  ],
  "Tsukiji & Toyosu": [
    hotel({
      id: "villa-shiodome",
      name: "Hotel Villa Fontaine Grand Tokyo Shiodome",
      area: "Tsukiji & Toyosu",
      lat: 35.6632,
      lng: 139.7605,
      blurb: "Between Shiodome and Tsukiji. A practical base if the outer market is the morning you care about.",
      priceBand: "Mid range",
      station: "Shiodome",
    }),
    hotel({
      id: "mitsui-ginza",
      name: "Mitsui Garden Hotel Ginza Premier",
      area: "Tsukiji & Toyosu",
      lat: 35.6678,
      lng: 139.7638,
      blurb: "On the Ginza side of Tsukiji, with the subway underneath and the market a walk away.",
      priceBand: "Splurge",
      station: "Shintomicho",
    }),
  ],
  "Shibuya & Harajuku": [
    hotel({
      id: "excel-tokyu",
      name: "Shibuya Excel Hotel Tokyu",
      area: "Shibuya & Harajuku",
      lat: 35.6588,
      lng: 139.699,
      blurb: "Sitting on Shibuya Station. Coming home is easy, and the desk will keep bags after checkout on the last day.",
      priceBand: "Splurge",
      station: "Shibuya",
    }),
    hotel({
      id: "trunk-shibuya",
      name: "Trunk(Hotel) Yoyogi Park",
      area: "Shibuya & Harajuku",
      lat: 35.6685,
      lng: 139.6925,
      blurb: "A smaller hotel between Shibuya and Harajuku, beside the park and Meiji Jingu.",
      priceBand: "Splurge",
      station: "Harajuku",
    }),
  ],
  Shinjuku: [
    hotel({
      id: "century-southern",
      name: "Hotel Century Southern Tower",
      area: "Shinjuku",
      lat: 35.6865,
      lng: 139.6995,
      blurb: "On the south side of Shinjuku Station. A reasonable one-night switch if you want to end in Golden Gai.",
      priceBand: "Mid range",
      station: "Shinjuku",
    }),
    hotel({
      id: "gracery-shinjuku",
      name: "Hotel Gracery Shinjuku",
      area: "Shinjuku",
      lat: 35.6954,
      lng: 139.7026,
      blurb: "In Kabukicho, a few minutes from Golden Gai. Only worth it if you are sleeping here on purpose.",
      priceBand: "Mid range",
      station: "Shinjuku",
    }),
  ],
  "Central Tokyo": [
    hotel({
      id: "mesm-tokyo",
      name: "Mesm Tokyo, Autograph Collection",
      area: "Central Tokyo",
      lat: 35.6655,
      lng: 139.7615,
      blurb: "In Shiodome, useful if you want Tokyo Station and Ginza without living inside either.",
      priceBand: "Splurge",
      station: "Shiodome",
    }),
  ],
  Kamakura: [
    hotel({
      id: "metropolitan-kamakura",
      name: "Hotel Metropolitan Kamakura",
      area: "Kamakura",
      lat: 35.3195,
      lng: 139.5502,
      blurb: "Across from Kamakura Station. Only book this if you want a slow morning. The default plan is a day trip.",
      priceBand: "Mid range",
      station: "Kamakura",
    }),
  ],
  Hakone: [
    hotel({
      id: "ten-yu",
      name: "Hakone Kowakien Ten-yu",
      area: "Hakone",
      lat: 35.2403,
      lng: 139.0442,
      blurb:
        "Every room has its own open-air hot spring, filled with Hakone spring water, looking over the valley. This is the private in-room bath. A free shuttle runs from Gora Station, so it is a longer ride than Yumoto with the bags. Dinner is usually included. Adding Hakone replaces two Tokyo nights.",
      priceBand: "Private open-air spring in every room · from about $550 for two · ¥80,000+",
      station: "Gora, then shuttle",
      mapsQuery: "Hakone Kowakien Ten-yu",
    }),
    hotel({
      id: "yumoto-fujiya",
      name: "Yumoto Fujiya Hotel",
      area: "Hakone",
      lat: 35.2328,
      lng: 139.1035,
      blurb:
        "Book the Superior Twin with Hot Spring if you want a private spring in the room. That bath is indoors. The other rooms use the shared indoor and outdoor baths, or a private bath you reserve for 45 minutes. The Romancecar ends at Hakone-Yumoto, and the desk can receive takkyubin.",
      priceBand: "Private indoor spring in one room type · about $250–450 · ¥40,000–70,000",
      station: "Hakone-Yumoto",
    }),
  ],
  Kyoto: [
    hotel({
      id: "granvia-kyoto",
      name: "Hotel Granvia Kyoto",
      area: "Kyoto",
      lat: 34.9855,
      lng: 135.7588,
      blurb: "Attached to Kyoto Station. The least fuss with shinkansen luggage, and a duller evening than downtown.",
      priceBand: "Splurge",
      station: "Kyoto",
    }),
    hotel({
      id: "cross-kyoto",
      name: "Cross Hotel Kyoto",
      area: "Kyoto",
      lat: 35.0038,
      lng: 135.7678,
      blurb: "Near Shijo, so dinner is outside the door. Ship bags here if you will sightsee before check-in.",
      priceBand: "Mid range",
      station: "Kawaramachi",
    }),
  ],
  Osaka: [
    hotel({
      id: "cross-osaka",
      name: "Cross Hotel Osaka",
      area: "Osaka",
      lat: 34.6726,
      lng: 135.5012,
      blurb: "In Shinsaibashi. Namba and Dotonbori are walkable, and the desk will hold bags.",
      priceBand: "Mid range",
      station: "Shinsaibashi",
    }),
  ],
  Nikko: [
    hotel({
      id: "kanaya-nikko",
      name: "Nikko Kanaya Hotel",
      area: "Nikko",
      lat: 36.753,
      lng: 139.602,
      blurb: "The old hotel above the shrines. Book it only if Nikko is an overnight, not a long day trip.",
      priceBand: "Splurge",
      station: "Nikko",
    }),
  ],
};

export function hotelsFor(zone: string): HotelOption[] {
  return HOTELS[zone] ?? [];
}
